//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace CartsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        [Display(Name = "商品名稱")]
        public string Name { get; set; }
        [Display(Name = "商品描述")]
        public string Description { get; set; }
        [Display(Name = "商品類別")]
        public string CategoryId { get; set; }
        [Display(Name = "商品價格")]
        public string Price { get; set; }
        [Display(Name = "建立日期")]
        public string PublishDate { get; set; }
        [Display(Name = "商品狀態")]
        public string Status { get; set; }
        [Display(Name = "商品圖片編號")]
        public string DefaultImageId { get; set; }
        [Display(Name = "庫存數量")]
        public string Quantity { get; set; }
        [Display(Name = "商品圖片URL")]
        public string DefaultImageURL { get; set; }
    }
}
